apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- receiver.yaml
- sender.yaml

secretGenerator:
- name: autoscale-credz
  namespace: autoscale-demo
  files:
  - sb_connection_string.txt