apiVersion: batch/v1
kind: Job
metadata:
  name: sb-queue-sender
  namespace: autoscale-demo
spec:
  ttlSecondsAfterFinished: 15
  template:
    spec:
      containers:
      - name: sb-queue-sender
        envFrom:
          - configMapRef:
              name: autoscale-config
          - secretRef:
              name: autoscale-credz
        image: sb-queue-sender
      restartPolicy: Never
